all:
  hosts:
    massage:
      ansible_connection: ssh
      ansible_user: "{{ remote_installer }}"
      ansible_become_pass: "{{ remote_installer_pw }}"
      ansible_host: massage.amer.irdeto.com
      ansible_port: 22
    massage_local:
      ansible_connection: local
      ansible_user: "{{ remote_installer }}"
      ansible_become_pass: "{{ remote_installer_pw }}"
